#!/usr/bin/env python
"""
A websocket server for das2 streams.  Written in python so we can ride off the dsdf
and dsif parsing to determine what command to run.
"""
import sys

g_sConfPath = REPLACED_ON_BUILD



import asyncio
import websockets

# create handler for each connection

async def handler(websocket, path):

	data = await websocket.recv()

	reply = f"Received {data} dude!"
	print("Handler run")
	print("Path: %s"%path)

	await websocket.send(reply)

 

start_server = websockets.serve(handler, "localhost", 52242)

 
asyncio.get_event_loop().run_until_complete(start_server)

asyncio.get_event_loop().run_forever()