#!/usr/bin/env python

import sys

#sys.stdout.write("Content-Type: text/plain; charset=utf-8\r\n\r\n")

import cgi
import cgitb
import time
import os.path
import os
import codecs
import traceback  

from io import StringIO        # handles unicode strings
from os.path import join as pjoin

g_sConfPath = REPLACED_ON_BUILD

def pout(item):
	"""If input item is bytes, write them, if item is a string
	encode as utf-8 first"""	
	if isinstance(item, str):
		sys.stdout.buffer.write(item.encode('utf-8'))
	else:
		sys.stdout.buffer.write(item)

##############################################################################
# Browser identification for use before util modules are loaded, after they 
# are loaded util.webio.g_lNotDas2App is used.  If you update this list, *also*
# update the list is util.io

_g_BrowserAgent = ['firefox','explorer','chrome','safari','edge']

#_g_siteTree = 'tag:das2.org,2012:site:/'
#_g_testTree = 'tag:das2.org,2012:test:/'

##############################################################################
# Default request handler map.  
#
# Here's the user-facing virtual filesystem presented by the server
#
# server/  An introductory html page
#   |
#   |- hapi/  - Heliophysics API subsystem (if enabled)
#   |
#   |- static/ - A blind directory (no output)
#   |    |
#   |    |- static files such as logos, etc
#   |
#   |- source/ - An html directory listing, useful for wget
#   |    |
#   |    |- juno.html - A display page for humans
#   |    |- juno.json - Top-level catalog node for Juno stuff
#   |    |- juno/ - An html directory listing for wget
#   |         |
#   |         |- wav.html  - A sub page for fumans
#   |         |- wav.json  - A sub level catalog node for Waves stuff
#   |         |- wav/ - An html directory listing for wget
#   |             |
#   |             |- survey.html - A query from for survey stuff
#   |             |- survey.json - A sub catalog node for Survey data sources
#   |             |- survey/ - An html directory listing, useful for wget
#   |                  |
#   |                  |- das2.d2t - the old dsdf as das2 stream trick
#   |                  |- flex.json - a fed cat HttpStreamSource object
#   |                  |- voservice.xml 
#   |                  |
#   |                  |- data - form action handler (hidden from indexes)
#   |
#   |- catalog.json  A das2 catalog listing of all items down to the
#   |     HttpStreamSource level, can feed URL to node.c as detached root
#   |
#   |- nodes.csv     A listing of all stand along catalog end points
#   |
#   |- root.json     The root node of the stand alone catalog points
#   |
#   |- verify - Included das2 stream verification tool
#   |
#   |- id.json - Server identification information
#   |- id.txt  - Old das2.2 info text
#   |- logo.png - Old das2.2 logo
#   |- peers.xml - A listing of peer servers
#
#
# To merge sources list here into a central catalog:
#
#  1) Pull root.json
#  2) Iterate through the levels merging information, creating collections

g_dDefHandlers = {

	# No path given
	'HANDLE_NONE':     'dasflex.handlers.intro',

	# ?server=debug /debug
	'HANDLE_DEBUG':    'dasflex.handlers.debug',

	# ?server=peers  /peers.xml
	'HANDLE_PEERS':    'dasflex.handlers.peers',

	# /static/*
	'HANDLE_RESOURCE': 'dasflex.handlers.resource',

	# ?server=logo  /logo.png
	'HANDLE_LOGO':   'dasflex.handlers.logo',

	# ?server=id    /id.txt  /id.json
	'HANDLE_ID':     'dasflex.handlers.id',
	
	# ?server=discovery ?server=list /catalog.json /nodes.csv /root.json
	'HANDLE_LIST':   'dasflex.handlers.catalog',
	
	# Effectively index.html files for wget... /source /static
	'HANDLE_DIR':      'dasflex.handlers.directory',

	# Directory info pages leading to a data source page
	'HANDLE_INFO':     'dasflex.handlers.info',

	# New flex requests: /source/juno/wav/survey.html
	'HANDLE_FORM':     'dasflex.handlers.d3form',

	# New das flex: /source/juno/wav/survey/flex (can handle others as well)
	'HANDLE_DATA':  'dasflex.handlers.d3data',

	# List of services offered by this server (failed experiment)
	#'HANDLE_SERVICES': 'dasflex.handlers.services',

	# /verify the validation service from & action
	'HANDLE_VERIFY': 'dasflex.handlers.verify',

	# Helophysics API substem
	'HANDLE_H_API_NONE':         'dasflex.h_api.root',
	'HANDLE_H_API_CAPS':         'dasflex.h_api.caps',
	'HANDLE_H_API_CATALOG' :     'dasflex.h_api.catalog',
	'HANDLE_H_API_INFO':         'dasflex.h_api.info',
	'HANDLE_H_API_DATA':         'dasflex.h_api.data'
}

##############################################################################
# Cut down version of error handling for use before the module path is loaded

def preLoadError(sOut):
	"""Cut down error handling for use before the util modules are loaded,
	script must exit after calling this or multiple HTTP headers will be 
	emitted.
	"""
	
	sType = 'InternalServerError'
	
	bClientIsBrowser = False
	if "HTTP_USER_AGENT" in os.environ:
		
		sAgent = os.environ['HTTP_USER_AGENT'].lower()
	
		for sTest in _g_BrowserAgent:
			if sAgent.find(sTest) != -1:
				bClientIsBrowser = True
				break	
	pout("Status: 500 Internal Server Error\r\n")
	
	if bClientIsBrowser:
		pout("Content-Type: text/plain; charset=utf-8\r\n\r\n")
		cgitb.enable(format='text')
		
		pout(sOut)
	else:
		pout("Content-Type: text/vnd.das2.das2stream\r\n\r\n")

		sOut = sOut.replace('\n', '\n\r').replace('"', "'")
		sOut = '<exception type="%s" message="%s" />\n'%(sType, sOut)
		xOut = sOut.encode('utf-8')
		pout("[00]%06d"%len(xOut))
		pout(xOut)


##############################################################################
# Get my config file, boiler plate that has to be re-included in each script
# since the location of the modules can be configured in the config file

def getConf():
	
	if not os.path.isfile(g_sConfPath):
		if os.path.isfile(g_sConfPath + ".example"):
			preLoadError("Move\n     %s.example\nto\n     %s\nto enable your site"%(
			      g_sConfPath, g_sConfPath))
		else:
			preLoadError("%s is missing\n"%g_sConfPath)
			
		return None

	# Yes, the Das2 server config files can contain unicode characters
	fIn = open(g_sConfPath, encoding='utf-8')
	
	dConf = {}
	nLine = 0
	for sLine in fIn:
		nLine += 1
		iComment = sLine.find('#')
		if iComment > -1:
			sLine = sLine[:iComment]
	
		sLine = sLine.strip()
		if len(sLine) == 0:
			continue
		
		iEquals = sLine.find('=')
		if iEquals < 1 or iEquals > len(sLine) - 2:
			preLoadError("Error in %s line %d"%(g_sConfPath, nLine))
			fIn.close()
			return None
		
		sKey = sLine[:iEquals].strip()
		sVal = sLine[iEquals + 1:].strip(' \t\v\r\n\'"')
		dConf[sKey] = sVal
	
	
	fIn.close()
	
	# As finial steps, inclued a reference to the config file itself
	dConf['__file__'] = g_sConfPath

	# Some replacement text
	if 'SERVER_ID' not in dConf:
		dConf['SERVER_ID'] = "unknown"

	if 'SERVER_NAME' not in dConf:
		dConf['SERVER_NAME'] = "Unknown"

	if 'SITE_CATALOG_TAG' not in dConf:
		dConf['SITE_CATALOG_TAG'] = "tag:unknown.site.org,2021"
	
	return dConf


##############################################################################
# Update sys.path, boiler plate code that has to be re-included in each script
# since config file can change module path

def setModulePath(dConf):
	if 'MODULE_PATH' not in dConf:
		preLoadError("Set MODULE_PATH = /dir/containing/dasflex_python_module")
		return False	
	
	lDirs = dConf['MODULE_PATH'].split(':') # No mater the os.pathsep setting
	for sDir in lDirs:
		if os.path.isdir(sDir):
				if sDir not in sys.path:
					sys.path.insert(0, sDir)
		
	return True


#############################################################################
# Look up a module and call it's handler function

def getHandler(U, fLog, dConf, sReqType):
	"""Return a handler module object.  This doesn't just return the handler
	function in the module because future handler interfaces my involve more
	than one function in the API"""
	
	if sReqType == None:
		U.webio.queryError(fLog, u"No handler for request type %s"%sReqType)
		return None

	if sReqType != 'HANDLE_RESOURCE':
		fLog.write("   Request Type: %s"%sReqType)
			
	# Take the handler from the conf, if not present, use the default
	if sReqType in dConf:
		sModule = dConf[sReqType]
	elif sReqType in g_dDefHandlers:
		sModule = g_dDefHandlers[sReqType]
	else:
		U.webio.notFoundError(fLog, "No handler for request type %s"%sReqType)
		return None
	
	if sModule.find('.') != -1:
		# If the module is in the form A.B.C then issue a load like
		# from A.B import C.
		
		iLastDot = sModule.rfind('.')
		if iLastDot >= len(sModule) - 2:
			U.webio.svrError("Bad handler for request %s: '%s'"%(
			                    sReqType, sModule), fLog)
			return None
				
		sModPath = sModule[:iLastDot]
		sModName = sModule[iLastDot + 1:]
		
		# Do an absolute import
		try:
			__import__(sModule, globals(), locals(), [], 0)
			module = sys.modules[sModule]
			
		except ImportError as e:
			U.webio.serverError(fLog, "Error loading module %s from %s: %s"%(
			                 sModName, sModPath, e))
			return None
		
	else:
		# If the module name is just a top level object do a call like
		# import A
		try:
			module = __import__(sModule, globals(), locals(), [], 0)
		except ImportError as e:
			U.webio.serverError(fLog, "Error loading module %s: %s"%(sModule, e))
			return None
	
	if sReqType != 'HANDLE_RESOURCE':
		fLog.write("   Handler: %s"%module.__file__)
	return module
	
#############################################################################
# Main

def main(form):

	rStartTime = time.time()

	pout("")
			
	dConf = getConf()
	if dConf == None:
		return 17
		
	# Set the system path
	if not setModulePath(dConf):
		return 18
		
	# Load the webutil module
	try:
		mTmp = __import__('dasflex', globals(), locals(), ['webutil'], 0)
	except ImportError as e:
		preLoadError(
			"Error importing module 'dasflex': %s\r\nsys.path is:\r\n%s\r\n"%(
			str(e), sys.path
		))
		return 19
	try:
		U = mTmp.webutil
	except AttributeError:
		preLoadError('No module named dasflex.webutil under %s'%dConf['MODULE_PATH'])
		return 20
		
	U.misc.envPathMunge("PATH", dConf['BIN_PATH'])
	U.misc.envPathMunge("LD_LIBRARY_PATH", dConf['LIB_PATH'])
	
	if 'LOG_PATH' in dConf:
		fLog = U.webio.DasLogFile(dConf['LOG_PATH'], os.getenv('REMOTE_ADDR'))
		#fLog.write("INFO: Logging to %s"%dConf['LOG_PATH'])
	else:
		fLog = U.webio.DasLogFile()

	#for sKey in list(dConf.keys()):
	#	fLog.write("%s = %s"%(sKey, dConf[sKey]))	
	
	for sEnv in ['SCRIPT_NAME', 'SERVER_NAME', 'QUERY_STRING']:
		if sEnv not in os.environ:
			preLoadError("Wierd Error, %s is not set in the script environment\r\n"%sEnv)
			return 21
	
	# Way up high, before anything Check the query parameters for obvious problems
	if not U.misc.checkParams(fLog, form):  # check for obvious problems, 
		U.webio.queryError(fLog, 
			"One or more of the query parameters looks like a shell injection "+\
			"attack, data output halted."
		)
		return 13


	sPathInfo = ''
	if os.getenv("PATH_INFO"):
		sPathInfo = os.getenv("PATH_INFO")
		
	if sPathInfo.find('..') != -1:
		U.webio.queryError(fLog, u"Bad Path")
		return 25
	
	# Don't log static resource requests, this just clutters up the logs
	if not sPathInfo.startswith('/static'):
		fLog.write("Input")
		fLog.write("   Request URL: %s"%U.webio.getUrl())
		fLog.write("   On Host: %s"%os.getenv('SERVER_NAME'))
		fLog.write("   For Program: %s"%os.getenv('SCRIPT_NAME'))
		fLog.write("   For Path: %s"%sPathInfo)
		fLog.write("   Parameters: %s"%os.getenv('QUERY_STRING'))
	
		if "HTTP_USER_AGENT" in os.environ:
			fLog.write("   User Agent: %s"%os.environ['HTTP_USER_AGENT'])
		else:
			fLog.write("   User Agent: Unknown (HTTP_USER_AGENT not given)")
	
		
	# Check to see that our resource path is sent and exist, or just 
	# exit with an error
	if not 'RESOURCE_PATH' in dConf:
		U.webio.serverError(fLog, u"Set the RESOURCE_PATH keyword in %s"%g_sConfPath)
		return 22
	
	if not os.path.isdir(dConf['RESOURCE_PATH']):
		U.webio.serverError(fLog, u"Can't locate resources, server path "
		      "%s doesn't exsit"%dConf['RESOURCE_PATH'])
		return 23
		
	# Handle Das2.2 style queries, except for the intro, these all have 
	# the server = keyword pattern
	sServer = form.getfirst('server', None)
	sReqType = None
	if sServer != None:
		sServer = sServer.lower()
		
		if sServer == 'list':
			sReqType = 'HANDLE_LIST'

		elif sServer == 'discovery':
			sReqType = 'HANDLE_LIST'
			
		elif sServer == 'dsdf':
			# For this one just re-write as a file request
			sLocalId = form.getfirst('dataset', 'nosuchset')
			sPathInfo = '/source/%s/das2.d2t'%(sLocalId.lower())
			sReqType = 'HANDLE_RESOURCE'
						
		elif sServer == 'logo':
			sReqType = 'HANDLE_LOGO'
	
		elif sServer == 'id':
			sReqType = 'HANDLE_ID'

		# Note as a das2 request and send to general das3 handler
		elif sServer in ['dataset', 'compactdataset']:
			sPathInfo = "/source/%s/das2"%(
				form.getfirst('dataset', 'nosuchset').lower()
			)
			sReqType = 'HANDLE_DATA'
	
		#elif sServer == 'image':
		#	sReqType = 'HANDLE_DSDF_IMAGE'
		
		elif sServer == 'peers':
			sReqType = 'HANDLE_PEERS'
			
		elif sServer == 'debug':
			sReqType = 'HANDLE_DEBUG'
		
		else:
			U.webio.queryError(fLog, "Bad server keyword.  Server must be "
	   	      "[dataset|dsdf|logo|list|discovery|logo|id|peers]\n")
					
	# If the path starts with '/hapi' send requests to subsystem handlers
	elif sPathInfo.startswith('/hapi'):
		sKey = "ENABLE_HAPI_SUBSYS"
		if (sKey not in dConf) or (dConf[sKey].lower() not in ('true','yes','1')):
			U.webio.queryError(fLog, u"Heliophysics API Subsystem not enabled, "+\
			 u"contact the server administrator if this feature is needed")
		
		else: 
			dTmp = {'/hapi/capabilities': 'HANDLE_H_API_CAPS',
					'/hapi/catalog':      'HANDLE_H_API_CATALOG',
					'/hapi/info':         'HANDLE_H_API_INFO',
					'/hapi/data':         'HANDLE_H_API_DATA' }
			for sKey in dTmp:
				if sPathInfo.startswith(sKey):
					sReqType = dTmp[sKey]
					break
					
			# Fall back, just send info page
			if sReqType is None:
				sReqType = 'HANDLE_H_API_NONE'
			
			
	# Handle DasFlex path oriented queries
	else:
		if sPathInfo in [None, '', '/']:
			sReqType = 'HANDLE_NONE'

		elif sPathInfo in ("/catalog.json", "/nodes.csv", "/root.json"):
			sReqType = 'HANDLE_LIST'
		
		elif sPathInfo == "/id.txt" or sPathInfo == "/id.json":
			sReqType = 'HANDLE_ID'
		
		elif sPathInfo == "/logo.png":
			sReqType = 'HANDLE_LOGO'

		elif sPathInfo.startswith('/peers.xml'):
			sReqType = 'HANDLE_PEERS'		
					
		elif sPathInfo.startswith('/debug'):
			sReqType = 'HANDLE_DEBUG'
		
		elif sPathInfo.startswith('/static'):
			sReqType = 'HANDLE_RESOURCE'		
		
		elif sPathInfo.startswith('/verify'):
			sReqType = 'HANDLE_VERIFY'

		elif sPathInfo.startswith('/source/'):
			if  sPathInfo.endswith('das2') or sPathInfo.endswith('flex'):
				sReqType = 'HANDLE_DATA'

			elif sPathInfo.endswith('/') or sPathInfo.endswith('index.html'):
				sReqType = 'HANDLE_DIR'
			elif sPathInfo.endswith('.html'):
				sReqType = 'HANDLE_FORM'
			elif sPathInfo.endswith('vodata'):
				sReqType = 'HANDLE_VOSERVICE'
			else:
				sReqType = 'HANDLE_RESOURCE'

		#elif sPathInfo.startswith('/coverage'):
		#	sReqType = 'HANDLE_COVERAGE'
	
	H = getHandler(U, fLog, dConf, sReqType)
	if H == None:
		return 25
	
	try:
		nRet = H.handleReq(U, sReqType, dConf, fLog, form, sPathInfo)
	except:
		fString = StringIO()
		traceback.print_exc(file=fString)
		sMsg = "\nException in handler: %s\n%s"%(H.__name__, fString.getvalue())
		U.webio.serverError(fLog, sMsg)
		nRet = 26
	
	sys.stdout.flush()
	if nRet != 0:
		fLog.write("\nError handling query, return value = %s"%nRet)
		return nRet
	
	rEndTime = time.time()
	rDuration = rEndTime - rStartTime
	if rDuration < 0.001:
		sDuration = "%.1f nanoseconds"%( rDuration * 1000000) 
	elif rDuration < 1.0:
		sDuration = "%.1f milliseconds"%( rDuration * 1000 )
	elif rDuration < 120.0:
		sDuration = "%.1f seconds"%rDuration
	else:
		sDuration = "%.2f minutes"%(rDuration / 60.0)
	
	if not sPathInfo.startswith('/static'):
		fLog.write("\nQuery handled without error in %s."%sDuration)
	return 0


##############################################################################
# Stub main for cgi

form = cgi.FieldStorage()

# Return values don't matter in CGI programming.  That's unfortunate
main(form)
